### ISSUE TITLE
LoggerLookupRegistration fails if you have multiple instances of ILogger registered

### ISSUE THREAD

**Issue by devonbessemer** [RockLib/RockLib.Logging#121]
`isSingletonLoggers` is assigned at the time of calling "AddLogger".  This fails when the count of ILogger instances does not match on execution of the LoggerLookupRegistration due to access of the index here: `!isSingletonLoggers[i]`.

It is common using the WebApplicationFactory from the ASP.NET Testing Framework to inject your own mock instance into the service container.  This leads to 2 ILoggers existing in the service container and this hard to debug exception being thrown:

```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at RockLib.Logging.DependencyInjection.ServiceCollectionExtensions.<>c__DisplayClass7_1.<SetLoggerLookupDescriptor>b__3(String name)
   at RockLib.Logging.RockLibLoggerProviderExtensions.<>c__DisplayClass3_0.<AddRockLibLoggerProvider>b__0(IServiceProvider serviceProvider) in /_/RockLib.Logging.Microsoft.Extensions/RockLibLoggerProviderExtensions.cs:line 82
```

https://github.com/RockLib/RockLib.Logging/blob/main/RockLib.Logging/DependencyInjection/ServiceCollectionExtensions.cs#L207
```csharp
        // Capture which loggers are singleton according to index.
        var isSingletonLoggers = services.Where(service => service.ServiceType == typeof(ILogger))
            .Select(service => service.Lifetime == ServiceLifetime.Singleton)
            .ToArray();

        LoggerLookup LoggerLookupRegistration(IServiceProvider serviceProvider) => name =>
        {
            // Select the first logger that has a matching name.
            var loggers = serviceProvider.GetServices<ILogger>().ToArray();
            var selectedLogger = loggers.First(logger => NamesEqual(logger.Name, name));

            // Immediately dispose any non-singleton loggers that weren't selected.
            for (var i = 0; i < loggers.Length; i++)
            {
                if (!isSingletonLoggers[i] && !ReferenceEquals(loggers[i], selectedLogger))
                {
                    loggers[i].Dispose();
                }
            }

            return selectedLogger;
        };
```

**Comment by motionsuggests** [comment]
@RockLib/maintainers Take a look please

**Comment by JasonBock** [comment]
Looking now.... @bessdt do you have a code snippet that can be used to reproduce the issue?

**Comment by bessdt** [comment]
@JasonBock You can reproduce it by adding another ILogger to the service container after calling AddLogger().   An example using the WebApplicationFactory from the the ASP.NET Testing Framework:

In Program.cs:
```csharp
builder.Services.AddLogger();
builder.Logging.AddRockLibLoggerProvider();
```

In test:
```csharp
var mockLogger = new Mock<ILogger>();
var app = new WebApplicationFactory<Program>().WithWebHostBuilder(builder =>
{
builder.ConfigureTestServices(services => { services.AddSingleton<ILogger>(mockLogger); });
});

// Resolve ILogger from IOC Container to reproduce runtime exception
application.Services.GetRequiredService<ILogger>();
```

**Comment by aatchison14** [comment]
@devonbessemer, RockLib.Logging 4.0.2 package has been released to address this bug.
